config/routes.rb
Rails.application.routes.draw do
  # remove lines 3 to 16, replace with line 16
  # 1.1 read
  get 'tasks', to: 'tasks#index'
  # 2.1 create
  get 'tasks/new', to: 'tasks#new', as: :task_create
  # 1.2 read 1
  get 'tasks/:id', to: 'tasks#show', as: :task
  # 2.2 create
  post 'tasks', to: 'tasks#create'
  # 3.1 edit @ update
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  # 3.2 update the edited version || add prefix
  patch 'tasks/:id', to: 'tasks#update', as: :task_update
  # 4.1 delete
  delete 'tasks/:id', to: 'tasks#destroy'
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_tasks, only: [:show, :edit, :update, :destroy]
  # read
  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  # # create
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  # edit @ update
  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    # item deleted so divert to the main page with all the list of items
    # status: 303 -> data is not available internally, see from external
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :detail %>
  <%= f.text_field :detail %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<div class="container">

<h1>Create Task</h1>

  <%= render 'form', task: @task %>

  <% end %>

  <%= link_to "Create Task", task_create_path %>

  <%= link_to "Edit Task", tasks_path %>
</div>


<%# <%= form_with model: @task do |f| %>
      <%# <%= f.label :title %>
      <%# <%= f.text_field :title %>

      <%# <%= f.label :detail %>
      <%# <%= f.text_field :detail %>

      <%# <%= f.label :completed %>
      <%# <%= f.text_field :completed %>

      <%# <%= f.submit %>
    <%# <% end %>

app/views/tasks/edit.html.erb
<div class="container">

<h1>Edit Task</h1>

  <%= render 'form', task: @task %>

  <% end %>

  <%= link_to "Back to Main Page", tasks_path %>
  <%= link_to "Create a task", task_create_path %>

</div>


<%# <%= form_with model: @task do |f| %>
      <%# <%= f.label :title %>
      <%# <%= f.text_field :title %>

      <%# <%= f.label :detail %>
      <%# <%= f.text_field :detail %>

      <%# <%= f.label :completed %>
      <%# <%= f.text_field :completed %>

      <%# <%= f.submit %>
    <%# <% end %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="banner">

  <h1>Display Tasks</h1>
  <hr>
    <ul>
      <% @tasks.each do |task| %>
        <li><%= link_to task.title, task_path(task) %></li>
      <% end %>
    </ul>

  <%= link_to "Create Task", task_create_path %>

  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a Task</h1>
  <div>
    <%= render 'form', task: @task %>
    <%= link_to "Create a new task", tasks_path %>
  </div>
</div>


<%# Task.create(title: "Studying", details: "A lot of flashcards to do", completed: true) %>


    <%# <%= form_with model: @task do |f| %>
      <%# <%= f.label :title %>
      <%# <%= f.text_field :title %>

      <%# <%= f.label :detail %>
      <%# <%= f.text_field :detail %>

      <%# <%= f.label :completed %>
      <%# <%= f.text_field :completed %>

      <%# <%= f.submit %>
    <%# <% end %>

app/views/tasks/show.html.erb
<div class="container">
  <h1>Task Created / Updated </h1>
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>
  <p><%= @task.completed%></p>

  <%= link_to "Return to main page", tasks_path %>
  <%= link_to "Edit task", task_edit_path %>
  <%= link_to "Create task", task_create_path %>

  <%# to delete %>
  <%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Task cleared?"}
  %>
</div>